### ISSUE TITLE
Error of running caevo

### ISSUE THREAD

**Issue by YuSawan** [Xingwei-Warwick/Set-Aligning-Event-Temporal-Graph-Generation#1]
I'm trying `run_caevo_on_dir.py`, but I'm encountering an error like the following and can't generate the graph.

```
Somethings are wrong about 1987_10_18_0083851.txt!
Somethings are wrong about 1999_02_06_1083038.txt!
Somethings are wrong about 2001_07_13_1308922.txt!
Somethings are wrong about 2001_12_12_1350656.txt!
Somethings are wrong about 1988_07_03_0158701.txt!
```

The cause seems to be related to caevo, and the errors are occurring even with `mvn test` as shown below:
```
Results :
Tests in error:
  testRawToTimex(caevo.TimexExtractionTest): ERROR: couldn't find JWNL xml properties file: null
  testRawToEvents(caevo.EventExtractionTest): ERROR: couldn't find JWNL xml properties file: null
  testWordnet(caevo.WordnetTest): ERROR: couldn't find JWNL xml properties file: null
```

Similar issues have been reported in caevo's issue([link](https://github.com/nchambers/caevo/issues/4#issue-505056258)), could you please advise on how to resolve them?

**Comment by Xingwei-Tan** [comment]
Dear YuSawn,

Thank you for being so interested in our project.
Although I am not entirely sure, the issue is probably due to the setup of CAEVO. 
Did you run [getwordnet.sh](https://github.com/nchambers/caevo/blob/master/getwordnet.sh)?
Based on the readme, it will set up the _jwnl_file_properties.xml_

I hope this could help🙂

**Comment by YuSawan** [comment]
Thank you for your reply.
I ran getwordnet.sh, and got the _jwnl_file_properties.xml_ to ~/wordnet3.1/

```
dict/
...
dict/cntlist
A new directory was created at ~/wordnet3.1
YOU MUST create an environment variable JWNL that points to ~/wordnet3.1/jwnl_file_properties.xml
Recommdation: add it to your .bashrc
```

But, this error even appears in `mv test`.
Where did you put wordnet3.1/?

**Comment by YuSawan** [comment]
I can load th JWNL file was set by exporting the global variable $JWNL.
`export  JWNL=~/wordnet3.1/jwnl_file_properties.xml`

Also, it seems that CAEVO is not compatible with Java 11. It looks like we can install the package by switching to Java 8. 

Though, I cannot run your run_caevo_on_dir.py yet with a error message in `caevo/runcaevoraw.sh`
```
❯ caevo/runcaevoraw.sh data/caevo_inputs/1987_01_01_0000149.txt
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.227 s
[INFO] Finished at: 2024-06-12T15:06:45+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.3.0:java (default-cli): Goal requires a project to execute but there is no POM in this directory (/path/to/Set-Aligning-Event-Temporal-Graph-Generation). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
```

**Comment by Xingwei-Tan** [comment]
Hi YuSawan,

I fixed a bug about the path issue. Not sure whether that can fix your current problem. Could you pull the latest code and try it?

Best,

**Comment by YuSawan** [comment]
Hi.
Thank you for fix bugs.

I ran your latest code, but the same error still occurs...
Though, adding some packages to caevo/pom.xml([link](https://github.com/xinsu626/caevo/blob/master/pom.xml)) seems to completely run the latest code!
```
❯ python run_caevo_on_dir.py --input-dir data/caevo_inputs/ --out-dir data/caevo_outputs/
1987_10_18_0083851.txt finished! 19284 left
1999_02_06_1083038.txt finished! 19283 left
```

**Comment by Xingwei-Tan** [comment]
As mentioned, the problem has been resolved. Closing the issue
